import { Container, Paper, Typography, Box, Divider } from '@mui/material';
import ReactMarkdown from 'react-markdown';

interface ReportContentProps {
  athleteName: string;
  content: string;
  createdAt: string;
}

export function ReportContent({ athleteName, content, createdAt }: ReportContentProps) {
  return (
    <Container maxWidth="md" sx={{ py: 4 }}>
      {/* Header */}
      <Box sx={{ textAlign: 'center', mb: 4 }}>
        <Typography
          variant="h4"
          sx={{ color: 'primary.main', fontWeight: 'bold', mb: 1 }}
        >
          AI Coach
        </Typography>
        <Typography variant="h5" gutterBottom>
          Progress Report
        </Typography>
        <Typography variant="body1" color="text.secondary">
          {athleteName}
        </Typography>
        <Typography variant="body2" color="text.secondary">
          {new Date(createdAt).toLocaleDateString('en-US', {
            weekday: 'long',
            year: 'numeric',
            month: 'long',
            day: 'numeric',
          })}
        </Typography>
      </Box>

      <Divider sx={{ mb: 4 }} />

      {/* Report Content */}
      <Paper sx={{ p: 4 }}>
        <Box
          sx={{
            '& p': { mb: 2, lineHeight: 1.7 },
            '& h1, & h2, & h3': { mt: 3, mb: 2 },
            '& ul, & ol': { pl: 3, mb: 2 },
            '& li': { mb: 1 },
            '& strong': { fontWeight: 600 },
            fontSize: '1.05rem',
          }}
        >
          <ReactMarkdown>{content}</ReactMarkdown>
        </Box>
      </Paper>

      {/* Footer */}
      <Box sx={{ mt: 4, textAlign: 'center' }}>
        <Typography variant="body2" color="text.secondary">
          This report was generated by AI Coach.
        </Typography>
        <Typography variant="body2" color="text.secondary">
          For questions, please contact your child's coach.
        </Typography>
      </Box>
    </Container>
  );
}
