import { Container, Paper, Typography, Box, Divider } from '@mui/material';
import ReactMarkdown from 'react-markdown';
import {
  MilestoneBanner,
  ProgressSnapshotCard,
  ReportProgressChart,
} from '../../components/reports';
import {
  ReportGraphDataPoint,
  ProgressSnapshot,
  Milestone,
} from '../../services/reports';

interface ReportContentProps {
  athleteName: string;
  content: string;
  createdAt: string;
  // New fields for enhanced parent reports
  graphData?: ReportGraphDataPoint[];
  progressSnapshot?: ProgressSnapshot | null;
  milestones?: Milestone[];
}

export function ReportContent({
  athleteName,
  content,
  createdAt,
  graphData = [],
  progressSnapshot = null,
  milestones = [],
}: ReportContentProps) {
  return (
    <Container maxWidth="md" sx={{ py: 4 }}>
      {/* Header */}
      <Box sx={{ textAlign: 'center', mb: 4 }}>
        <Typography
          variant="h4"
          sx={{ color: '#000000', fontWeight: 'bold', mb: 1 }}
        >
          CoachAI Progress Report
        </Typography>
        <Typography variant="body1" color="text.secondary">
          {athleteName}
        </Typography>
        <Typography variant="body2" color="text.secondary">
          {new Date(createdAt).toLocaleDateString('en-US', {
            weekday: 'long',
            year: 'numeric',
            month: 'long',
            day: 'numeric',
          })}
        </Typography>
      </Box>

      <Divider sx={{ mb: 4 }} />

      {/* Milestone Banner (if any achievements) */}
      {milestones && milestones.length > 0 && (
        <Box sx={{ mb: 4 }}>
          <MilestoneBanner milestones={milestones} />
        </Box>
      )}

      {/* Progress Snapshot Card */}
      {progressSnapshot && (
        <Box sx={{ mb: 4 }}>
          <ProgressSnapshotCard snapshot={progressSnapshot} />
        </Box>
      )}

      {/* Balance Hold Time Graph */}
      {graphData && graphData.length > 0 && (
        <Box sx={{ mb: 4 }}>
          <ReportProgressChart graphData={graphData} />
        </Box>
      )}

      {/* AI Narrative Content */}
      <Paper
        elevation={0}
        sx={{
          p: 4,
          borderRadius: 3,
          backgroundColor: '#FFFFFF',
          border: '1px solid #E5E5E5',
          boxShadow: '0 2px 8px rgba(0, 0, 0, 0.08)',
        }}
      >
        <Typography
          variant="h6"
          sx={{
            fontWeight: 600,
            color: '#2D2D2D',
            mb: 3,
            fontSize: '1.125rem',
          }}
        >
          Coach's Notes
        </Typography>
        <Box
          sx={{
            '& p': { mb: 2, lineHeight: 1.7, color: '#2D2D2D' },
            '& h1, & h2, & h3': { mt: 3, mb: 2, color: '#2D2D2D' },
            '& ul, & ol': { pl: 3, mb: 2 },
            '& li': { mb: 1, color: '#2D2D2D' },
            '& strong': { fontWeight: 600 },
            fontSize: '1rem',
          }}
        >
          <ReactMarkdown>{content}</ReactMarkdown>
        </Box>
      </Paper>

      {/* Footer */}
      <Box sx={{ mt: 4, textAlign: 'center' }}>
        <Typography variant="body2" sx={{ color: '#6B6B6B' }}>
          This report was generated by CoachAI.
        </Typography>
        <Typography variant="body2" sx={{ color: '#6B6B6B' }}>
          For questions, please contact your child's coach.
        </Typography>
      </Box>
    </Container>
  );
}
