"""Parent report email template."""


def get_report_email_html(
    athlete_name: str,
    coach_name: str,
    report_url: str,
    pin: str
) -> str:
    """Generate HTML email for parent report.

    Args:
        athlete_name: Name of the athlete
        coach_name: Name of the coach
        report_url: URL to view the report
        pin: 6-digit PIN for access

    Returns:
        str: HTML email content
    """
    return f"""
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
        <h2 style="color: #1976d2;">Progress Report Available</h2>

        <p>Hello,</p>

        <p>Coach <strong>{coach_name}</strong> has shared a progress report for <strong>{athlete_name}</strong>.</p>

        <p>This report includes insights from recent athletic assessments using AI Coach, including balance test results and development progress.</p>

        <div style="background-color: #f5f5f5; border-radius: 8px; padding: 20px; margin: 20px 0; text-align: center;">
            <p style="margin-bottom: 15px;"><strong>Your Access PIN:</strong></p>
            <p style="font-size: 32px; font-weight: bold; letter-spacing: 8px; color: #1976d2; margin: 0;">
                {pin}
            </p>
        </div>

        <p style="text-align: center; margin: 30px 0;">
            <a href="{report_url}"
               style="background-color: #1976d2; color: white; padding: 14px 28px;
                      text-decoration: none; border-radius: 6px; display: inline-block;
                      font-weight: bold;">
                View Progress Report
            </a>
        </p>

        <p style="color: #666; font-size: 14px;">
            You'll need to enter the PIN above to view the report. This helps keep {athlete_name}'s information private.
        </p>

        <hr style="border: none; border-top: 1px solid #eee; margin: 30px 0;">

        <p style="color: #888; font-size: 12px;">
            This report was generated by AI Coach on behalf of {coach_name}.
            If you have questions about the report, please contact the coach directly.
        </p>
    </div>
    """


def get_report_email_subject(athlete_name: str) -> str:
    """Generate email subject line.

    Args:
        athlete_name: Name of the athlete

    Returns:
        str: Email subject
    """
    return f"Progress Report for {athlete_name} - AI Coach"
